"use client";
import "./globals.css";
import { store } from "./redux/app/store";
import { Provider } from "react-redux";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Home Page</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <Provider store={store}>
        <body id="__next">{children}</body>
      </Provider>
    </html>
  );
}
